### ISSUE TITLE
Not working with react native 

### ISSUE THREAD

**Issue by Urwa9550** [maxdeviant/redux-persist-transform-encrypt#71]
![simulator_screenshot_3E1468C2-C76D-42DA-9FF0-B2CFDE75D951](https://github.com/maxdeviant/redux-persist-transform-encrypt/assets/49881172/3819cf94-abc4-43a9-aa4d-60515c69b3b7)

**Comment by maxdeviant** [comment]
@Urwa9550 Could you let me know what version of the library you are seeing the error with?

Note that as of `v5.0.0` the package is ESM only: https://github.com/maxdeviant/redux-persist-transform-encrypt/releases/tag/v5.0.0

**Comment by radelcom** [comment]
also seeing this error. jest unit testings is also complaining about 
```
Cannot find module 'redux-persist-transform-encrypt'
```

**Comment by maxdeviant** [comment]
> also seeing this error. jest unit testings is also complaining about
> 
> ```
> Cannot find module 'redux-persist-transform-encrypt'
> ```

Jest does not natively support ESM.

There is experimental support: https://jestjs.io/docs/ecmascript-modules

**Comment by radelcom** [comment]
> > also seeing this error. jest unit testings is also complaining about
> > ```
> > Cannot find module 'redux-persist-transform-encrypt'
> > ```
> 
> Jest does not natively support ESM.
> 
> There is experimental support: https://jestjs.io/docs/ecmascript-modules

thanks @maxdeviant, I'll take a look at that link. However, I am also seeing OPs issue when trying to run the app locally. Do we need to configure something in the react-native side to get ESM module to work?

**Comment by jackkrone** [comment]
Had the same issue with v5. Now using 3.0.1 without issue

**Comment by ThushalIntervest** [comment]
same issue when updated to 3.0.1 -> 5.0.0
Any one has a solution?

**Comment by apbarratt** [comment]
Hi guys, I've create a PR with a change that fixed this for us, however, I don't think it's really the correct solution.

The trouble we're having comes from Metro, where it states that the package.json file for this package specifically has a `"main": "index.js",`, which is not true.  It now uses esm module stuff.

So my "fix" is to just add in `"main": "lib/index.js",` which solves the problem, but I just don't have enough knowledge of esm module stuff to know if this might become a hinderence elsewhere.  Especially given this really sounds more like an issue with packages such as metro than anything else.

In the mean time, the _true_ fix we are using right now is to import the library directly using
`import { encryptTransform } from 'redux-persist-transform-encrypt/lib';` (note the `/lib` on the end)

**Comment by apbarratt** [comment]
Here is a screenshot of the error that we get on our phones when we load this on iOS (I'm told it's happening on Android too, but I haven't set up my android build environment quite yet).  Curiously the bundle builds just fine for web using metro as usual.
![IMG_1437](https://github.com/maxdeviant/redux-persist-transform-encrypt/assets/642320/501270de-bad9-448b-8ed0-3cb1cd29eda2)

**Comment by apbarratt** [comment]
I figured I'd check another package and the natural choice was `redux-persist`

There the package.json does indeed contain both `module` and `main` lines.  So perhaps I'm on the right track after all.

```
{
  "name": "redux-persist",
  "version": "6.0.0",
  "description": "persist and rehydrate redux stores",
  "main": "lib/index.js",
  "module": "es/index.js",
  "types": "./types/index.d.ts",
  "repository": "rt2zz/redux-persist",
  ...
```

**Comment by yamiyukiharu** [comment]
Hi everyone, Im facing this issue as well, what is the recommended temporary solution?

**Comment by maxdeviant** [comment]
> Hi everyone, Im facing this issue as well, what is the recommended temporary solution?

Please try out [v5.1.0](https://github.com/maxdeviant/redux-persist-transform-encrypt/releases/tag/v5.1.0) and see if that fixes the issue for you.

**Comment by yamiyukiharu** [comment]
hey @maxdeviant , thanks for the quick reply. Tried that and still facing the same issue unfortunately.
